apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-argo-application
  namespace: argocd
spec:
  project: default

stringData:
  source:
    repoURL: https://github.com/Plintron-Microservices-Org/vote.git
    targetRevision: HEAD
    path: k8s-specifications
    password: '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'
    username: 'Nayana-Nagaraj'
  destination: 
    server: https://kubernetes.default.svc
    namespace: vote

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
