apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vote-app
  namespace: argocd-1
spec:
  project: default

  source:
    repoURL: https://github.com/Plintron-Microservices-Org/vote.git
    targetRevision: HEAD
    path: ./k8s-specifications
  destination: 
    server: https://kubernetes.default.svc
    namespace: vote

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
