name: Argocd-u

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:

  deploy-UAT-docker-image:
    runs-on: plintron
    if: ${{ github.head_ref	== 'refs/heads/UAT'|| github.ref == 'refs/heads/UAT' }}
    steps:
    - uses: actions-hub/kubectl@master
      env:
       KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
      with:
       args: apply -f argo.yaml 
       
  deploy-prod-docker-image:
    runs-on: plintron
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
    - uses: actions-hub/kubectl@master
      env:
       KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
      with:
       args: apply -f argo.yaml 
  
    
