name: Build and deploy application through ArgoCd

on:
  push:
    branches:
      - UAT
  pull_request:
    branches: 
      - UAT
  workflow_dispatch:
  # A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Build Steps
        run: echo "Build Steps Here"
  
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
     name: 'UAT'

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           aws-region: us-east-2
           
      - name: initalize cluster
        id: install-aws-cli
        uses: unfor19/install-aws-cli-action@master
        with:
         version: 2  
      - run: aws eks --region us-east-2 update-kubeconfig --name eks-cluster
      - run: kubectl apply -f argo.yaml
